name: Simple CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Test if HTML is valid
    - name: Test HTML files
      run: |
        echo "Checking if HTML files exist..."
        ls -la *.html
        echo "✅ HTML files found!"

    # Step 3: Test if CSS files exist
    - name: Test CSS files
      run: |
        echo "Checking if CSS files exist..."
        if [ -f "style.css" ]; then
          echo "✅ style.css found!"
        else
          echo "❌ style.css missing!"
          exit 1
        fi

    # Step 4: Test if JavaScript files exist
    - name: Test JS files
      run: |
        echo "Checking if JavaScript files exist..."
        if [ -f "script.js" ]; then
          echo "✅ script.js found!"
        else
          echo "❌ script.js missing!"
          exit 1
        fi

    # Step 5: Simple deployment simulation
    - name: Deploy simulation
      run: |
        echo "🚀 Deploying website..."
        echo "All tests passed! Ready for deployment."
        echo "Website would be deployed now!"
